name: TrustEnderChest
main: fun.lonix.holyenderchest.HolyEnderChest
version: 1.0
api-version: 1.16
author:
  - markizkas
  - Lonix
website:
  - https://t.me/TrustDevs
depend:
  - PlayerPoints
commands:
  ec:
    description: Открыть эндер-сундук
    usage: /ec
    permission: minestashenderchestupgrade.ec
    aliases: [enderchest]
  enderchest:
    description: Открыть эндер-сундук
    usage: /enderchest
    permission: minestashenderchestupgrade.ec

permissions:
  minestashenderchestupgrade.ec:
    description: Разрешает использовать эндер-сундук
    default: true
  minestashenderchestupgrade.ec.admin:
    description: Разрешает использовать админские команды
    default: op
    children:
      - minestashenderchestupgrade.ec
  minestashenderchestupgrade.ec.view:
    description: Разрешает просматривать эндер-сундуки других игроков
    default: op
  minestashenderchestupgrade.ec.take:
    description: Позволяет забирать предметы из чужого эндер-сундука

    default: op
